dist: xenial
addons:
    snaps:
        - name: dotnet-sdk
          confinement: classic
          channel: latest/beta
sudo: required
language: csharp
mono: none
install:
    - sudo snap alias dotnet-sdk.dotnet dotnet
    - dotnet restore
    - touch log.txt
script:
    - dotnet build
    - dotnet test
