branches:
    except:
    - no-function-editor
    only:
    - master
    - /^.*-development$/
dist: xenial
addons:
    snaps:
        - name: dotnet-sdk
          confinement: classic
          channel: latest/beta
sudo: required
language: csharp
mono: none
install:
    - sudo snap alias dotnet-sdk.dotnet dotnet
    - dotnet restore src/MikeDev.sln
script:
    - dotnet build src/MikeDev.sln
    - dotnet test src/MikeDev.Test/MikeDev.Test.csproj
