# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

variables:
  solution: 'src/MikeDev.sln'
  testLocation: 'src/MikeDev.Test/'
  testProject: '$(testLocation)MikeDev.Test.csproj'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreInstaller@0
  inputs:
    version: '3.0.100-preview-010184'

- script: dotnet restore $(solution)

- script: dotnet build $(solution) -p:Configuration=$(buildConfiguration)

- script: dotnet test $(testProject) -p:Configuration=$(buildConfiguration)